name: Deploy
on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [update_post]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      run: |
        touch .env
        echo "SERVICE_DOMAIN=${{ secrets.SERVICE_DOMAIN }}" >> .env
        echo "API_KEY=${{ secrets.API_KEY }}" >> .env
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install
    - run: yarn generate