name: Deploy
on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [update_post]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install
    - run: |
        touch .env
        echo "SERVICE_DOMAIN=${{ secrets.SERVICE_DOMAIN }}" >> .env
        echo "API_KEY=${{ secrets.API_KEY }}" >> .env
        cat .env
    - run: yarn generate
    - name: git setting
      run: |
        git config --local user.email "mgk.webcreate@gmail.com"
        git config --local user.name "gkNorth"
    - name: Commit files
      run: |
        git pull
        git add .
        git commit -m "change from cms"
        git push origin master